### ISSUE TITLE
eu-west-1 cloudspecs are missing attributes

### ISSUE THREAD

**Issue by WojciechDolata** [aws-cloudformation/cfn-lint#2552]
### CloudFormation Lint Version

cfn-lint 0.61.1

### What operating system are you using?

Ubuntu

### Describe the bug

The cloud specs for eu-west-1 in the latest updates (started on 06.01 for us) are missing properties "Endpoint.Address" and "Endpoint.Port" for the DB Cluster. See https://github.com/aws-cloudformation/cfn-lint/pull/2530/files#diff-9a28967f4b88d91a4b8773284334dbc62e8fb7255bf297fdb189108a7dbba6d4L5074

Our CI started failing with `E1010 Invalid GetAtt DbCluster.Endpoint.Port for resource <someResource>`
 since we use those properties in our cloudformation templates.

### Expected behavior

Using DBCluster's "Endpoint.Address" and "Endpoint.Port" properties' shouldn't fail cfn-lint

### Reproduction template

.

Issue similiar to: https://github.com/aws-cloudformation/cfn-lint/issues/2343

**Comment by kddejong** [comment]
This is resolved in more recent versions of cfn-lint.  Can you upgrade to our most recent release [version](https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.72.6)?

You may also be able to fix this by running `cfn-lint --update-specs`

**Comment by WojciechDolata** [comment]
I've updated cfn-lint to cfn_lint-0.72.7-py3-none-any.whl (latest) and did cfn-lint --update-specs and the issue persists

**Comment by WojciechDolata** [comment]
We had older python, but after bumping everything to be up to date, the issue is gone, thanks for support
